# Generated by Django 2.2.20 on 2021-06-14 16:44

from django.db import migrations

MIN_CONSTRUCTION_YEAR = 2015


def set_new_building_property(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.filter(construction_year__gte=MIN_CONSTRUCTION_YEAR).update(new_building=True)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(set_new_building_property)
    ]
