# Generated by Django 2.2.20 on 2021-06-14 16:44

from django.db import migrations

MIN_CONSTRUCTION_YEAR = 2015


def set_new_building_property(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all().iterator():
        is_new_building = flat.construction_year >= MIN_CONSTRUCTION_YEAR
        flat.new_building = is_new_building
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(set_new_building_property)
    ]
