# Generated by Django 2.2.20 on 2021-06-16 13:33
import phonenumbers

from django.db import migrations


def set_owner_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all().iterator():
        phone_number = phonenumbers.parse(flat.owners_phonenumber, "RU")
        if phonenumbers.is_valid_number(phone_number):
            pure_phone = phonenumbers.format_number(phone_number, phonenumbers.PhoneNumberFormat.E164)
            flat.owner_pure_phone = pure_phone
            flat.save()


def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.all().update(owner_pure_phone=None)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(set_owner_pure_phone, move_backward)
    ]
