# Generated by Django 2.2.20 on 2021-06-16 15:43

from django.db import migrations


def fill_flat_owners(apps, scheme_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner, created = Owner.objects.get_or_create(owner=flat.owner, owners_phonenumber=flat.owners_phonenumber,
                                                     owner_pure_phone=flat.owner_pure_phone)
        owner.owner_flats.add(flat)
        owner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_owner'),
    ]

    operations = [
        migrations.RunPython(fill_flat_owners)
    ]
