# Generated by Django 2.2.20 on 2021-06-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20210616_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
        migrations.AddField(
            model_name='flat',
            name='owner',
            field=models.ManyToManyField(related_name='Владелец', to='property.Owner'),
        ),
    ]
