# Generated by Django 2.2.20 on 2021-06-16 17:04

from django.db import migrations


def set_flat_owners(apps, scheme_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all().iterator():
        for owner_flat in owner.owner_flats.all():
            flat = Flat.objects.get(id=owner_flat.id)
            flat.owner.add(owner)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20210616_2000'),
    ]

    operations = [
        migrations.RunPython(set_flat_owners)
    ]
