# Generated by Django 2.2.20 on 2021-08-01 09:36

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_auto_20210801_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='text',
            field=models.TextField(blank=True, default='', verbose_name='Текст жалобы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None, verbose_name='Нормализованный номер телефона'),
            preserve_default=False,
        ),
    ]
